export VLLM_ATTENTION_BACKEND=XFORMERS
export PYTHONPATH=$PYTHONPATH:/home/luban/Megatron-LM
output_dir=/nfs/volume-1615-1/lilinchuan/tmp-data/grpo_out
export TENSORBOARD_DIR=/nfs/volume-1615-1/lilinchuan/tmp-data/tb/qwen2_7b_rm_vllm_1
export VERL_PPO_LOGGING_LEVEL=INFO

model_path=/nfs/volume-1615-2/models/Meta-Llama-3.1-8B-Instruct
# model_path=/nfs/volume-1615-2/models/Qwen2-7B-Instruct
rm_model_path=/nfs/volume-1615-2/models/Qwen2.5-7B-Instruct

python3 -m verl.trainer.main_ppo \
    --config-path=./config --config-name='grpo_fsdp_rm_vllm' \
    algorithm.adv_estimator=grpo \
    algorithm.kl_ctrl.kl_coef=0.001 \
    data.train_files=data/gsm8k/train.parquet \
    data.val_files=data/gsm8k/test.parquet \
    data.train_batch_size=1024 \
    data.val_batch_size=1312 \
    data.max_prompt_length=512 \
    data.max_response_length=1024 \
    actor_rollout_ref.model.path=${model_path} \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=7680 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.model.path=${rm_model_path} \
    reward_model.has_validate_fn=True \
    reward_model.generate.custom_fn_file='gsm8k_rm' \
    trainer.critic_warmup=0 \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name='verl_grpo_gsm8k_rm' \
    trainer.experiment_name='qwen2_7b_rm_vllm_1' \
    +trainer.val_before_train=True \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=-1 \
    trainer.test_freq=5 \
    trainer.total_epochs=1 $@