export VLLM_ATTENTION_BACKEND=XFORMERS
export WANDB_API_KEY=32b85f731210a303efe3a8d1ba11369f6c23d5dd
# export CUDA_VISIBLE_DEVICES='4,5,6,7'
export PYTHONPATH=$PYTHONPATH:/tmp-data/Megatron-LM-v0.11.0
export TMPDIR=/tmp-data
output_dir=/nfs/ofs-llm-ssd/user/fengyu/models/Qwen2.5-7B-grpo-ori
cd /nfs/ofs-llab-volume/users/fengyu/new_verl/verl

# ray job submit --address="http://127.0.0.1:8265" \
    # -- python3 -m verl.trainer.main_ppo  --config-name='ppo_trainer.yaml' \
python3 -m recipe.partial_rollout.main_ppo_partial_rollout \
    algorithm.adv_estimator=grpo \
    data.train_files=/nfs/ofs-llab-volume/users/fengyu/data/train.parquet \
    data.val_files=/nfs/ofs-llab-volume/users/fengyu/data/test.parquet \
    data.train_batch_size=32 \
    data.max_prompt_length=512 \
    data.max_response_length=150 \
    actor_rollout_ref.model.path=/nfs/volume-1615-2/models/Qwen2.5-0.5B \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24000 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console'] \
    trainer.project_name='verl_grpo_example_gsm8k' \
    trainer.experiment_name='qwen2_7b_function_rm_kl1e-3' \
    +trainer.val_before_train=False \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=-1 \
    trainer.test_freq=-1 \
    trainer.total_epochs=15
